on: push
name: Espace danse
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Upload Files
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ftp.cluster010.hosting.ovh.net
        username: espacedar
        password: ${{ secrets.FTPPASSWORD }}
        localDir: '.'
        remoteDir: '/www/'
