on: push
name: Espace danse
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.5
      with:
        host: 'ftp.cluster010.hosting.ovh.net'
        port: 22
        username: 'espacedar'
        password: ${{ secrets.FTPPASSWORD }}
        remotePath: 'www/'
